### ISSUE TITLE
code

### ISSUE THREAD

**Issue by stu977** [colinzhaoxp/CDSM#3]
Hi author, I encountered a problem running the code，What is the setting of this parameter

Traceback (most recent call last):
  File "examples/train.py", line 478, in <module>
    main()
  File "examples/train.py", line 151, in main
    main_worker(args)
  File "examples/train.py", line 176, in main_worker
    model, model_ema = create_model(args)
  File "examples/train.py", line 114, in create_model
    num_classes=0, pooling_type=args.pooling_type, mlp=args.mlp)
AttributeError: 'Namespace' object has no attribute 'mlp'

**Comment by colinzhaoxp** [comment]
Hello, the parameter was left by other ideas, and it's OK just remove it. 
Now the code has been updated.

**Comment by stu977** [comment]
> Hello, the parameter was left by other ideas, and it's OK just remove it. Now the code has been updated.

Thank you
